=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/json_schemas/service_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Service name identifier"
    },
    "tag": {
      "type": "string",
      "description": "tag",
      "default": ""
    },
    "className": {
      "type": "string",
      "enum": ["Connection"],
      "default": ""
    },
    "connGroup": {
      "type": "string",
      "default": ""
    },
    "customer": {
      "type": "string",
      "description": "customer name",
      "default": ""
    },
    "protection": {
      "type": "boolean",
      "description": "Whether the service is protected or not",
      "default": false
    },
    "hierarchicalLevel": {
      "type": "string",
      "enum": ["service"],
      "description": "Detail of the level in architecture hierarchy"
    },
    "configurationState": {
      "type": "string",
      "enum": ["defined", "routed", "implemented"],
      "description": "Detail of state of configurationState",
      "default": "implemented"
    },
    "connLps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "className": {
            "type": "string",
            "enum": ["ConnLpEthCbr"],
            "description": "className of LTP Connection"
          },
          "rate": {
            "type": "string",
            "enum": ["1Gb", "10Gb"],
            "description": "Connection rate"
          },
          "fecType": {
            "type": "string",
            "enum": ["automatic", "noFec", "rsFec"],
            "description": "Forward Error Correction type",
            "default": "automatic"
          }
        },
        "required": ["className", "rate"]
      }
    },
    "connEndPoints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "className": {
            "type": "string",
            "enum": ["ConnEndPoint"]
          },
          "ltp": {
            "type": "object",
            "properties": {
              "className": {
                "type": "string",
                "enum": ["Ltp"]
              },
              "id": {
                "type": "integer",
                "description": "integer ID of the source/sink node"
              }
            }
          }
        },
        "endType": {
          "type": "string",
          "enum": ["source", "sink"]
        }
      }
    },
    "routingCriteria": {
      "type": "string",
      "enum": ["byLength", "byHops", "byAdministrativeCost"],
      "description": "Routing method to use in path calculation algorithm"
    },
    "sncpInfo": {
      "type": "object",
      "properties": {
        "holdOffTime": {
          "type": "integer",
          "description": "Hold off time",
          "default": 0
        },
        "revertive": {
          "type": "boolean",
          "description": "Revertive or not revertive",
          "default": true
        },
        "sncpType": {
          "type": "string",
          "enum": ["sncp_n", "sncp_i"],
          "default": "sncp_i",
          "description": "Subnetwork Connection Protection"
        },
        "wtrTime": {
          "type": "integer",
          "description": "Waiting Time",
          "default": 300
        }
      },
      "required": ["holdOffTime", "revertive", "sncpType", "wtrTime"]
    },
    "pm": {
      "type": "object",
      "properties": {
        "cd15m": {
          "type": "string",
          "enum": ["disabled", "enabledCurrent", "enabledCurrentAndArchive"],
          "description": "cd15m state"
        },
        "cd24h": {
          "type": "string",
          "enum": ["disabled", "enabledCurrent", "enabledCurrentAndArchive"],
          "description": "cd24h state"
        }
      }
    },
    "pmode": {
      "type": "object",
      "properties": {
        "provisioned": {
          "type": "string",
          "description": "pm mode provision",
          "default": ""
        }
      }
    },
    "asapSelectionProfile": {
      "type": "object",
      "properties": {
        "isDefault": {
          "type": "boolean",
          "default": true
        },
        "name": {
          "type": "string",
          "default": ""
        }
      }
    },
    "alarmMode": {
      "type": "string",
      "default": ""
    },
    "extendedAlarmMode": {
      "type": "string",
      "default": ""
    },
    "tcaTranspProfile15": {
      "type": "object",
      "properties": {
        "isDefault": {
          "type": "boolean",
          "default": true
        },
        "name": {
          "type": "string",
          "default": ""
        }
      }
    },
    "tcaTranspProfile24": {
      "type": "object",
      "properties": {
        "isDefault": {
          "type": "boolean",
          "default": true
        },
        "name": {
          "type": "string",
          "default": ""
        }
      }
    }
  },
  "required": [
    "className",
    "connEndPoints",
    "routingCriteria",
    "sncpInfo",
    "connLps",
    "configurationState",
    "hierarchicalLevel",
    "name",
    "protection"
  ]
}

=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/test_set/ground_truths/answer_29.json
[
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2272
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2300
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "Node2-1G-service-Node1",
    "protection": false
  },
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2302
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2360
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "10Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "Node3-1G-service-Node1",
    "protection": false
  }
]

=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/test_set/ground_truths/answer_8.json
[
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2272
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2300
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "S-Node1-Node2",
    "protection": true
  },
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2274
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2360
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "10Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "S-Node1-Node3",
    "protection": false
  }
]

=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/test_set/ground_truths/answer_15.json
[
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2272
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2360
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "defined",
    "hierarchicalLevel": "service",
    "name": "Node1-service-Node3",
    "protection": false
  }
]

=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/test_set/ground_truths/answer_35.json
[
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2300
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2272
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "Node2-service-Node1",
    "protection": true
  },
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2360
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2302
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "s-Node3-Node2,",
    "protection": true
  }
]

=== bonsai-lab-polimi/ecoc2024-llm-orchestrator/data/test_set/ground_truths/answer_32.json
[
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2360
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2272
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "Node3-service-Node1",
    "protection": false
  },
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2300
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2274
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "service-Node2-Node1",
    "protection": false
  },
  {
    "className": "Connection",
    "connEndPoints": [
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2302
        },
        "endType": "source"
      },
      {
        "className": "ConnEndPoint",
        "ltp": {
          "className": "Ltp",
          "id": 2362
        },
        "endType": "sink"
      }
    ],
    "routingCriteria": "byLength",
    "sncpInfo": {
      "holdOffTime": 0,
      "revertive": true,
      "sncpType": "sncp_i",
      "wtrTime": 300
    },
    "connLps": [
      {
        "className": "ConnLpEthCbr",
        "rate": "1Gb"
      }
    ],
    "configurationState": "implemented",
    "hierarchicalLevel": "service",
    "name": "Node2-Node3-service",
    "protection": false
  }
]
